Ping/Ping.py, simplePingExample.py
- Correct imports
- Correct prints
- Add compatibility between python2 and python3
=> Random corrections to allow python2/3 compatibility 

.travis.yml
This should deploy tags automatically.
Fix #26
=> Setup automated deploy with Travis

setup.py
=> Setup.py: add 'future' as a requirement

.travis.yml, setup.py, test-ci.py
=> travis: try to resolve pypi deployment

brping/ping1d.py
This reduces the CPU usage on a Pi Zero to around 10% when polling at 10Hz with the simplePingExample.py
=> Reduce CPU usage

tools/ping1d-simulation.py
This makes things work after switching ping-viewer to general_request
=> Request update

generate/templates/device.py.in
=> templates: device: Simplify return

generate/templates/device.py.in, generate/templates/ping1d.py.in, generate/templates/ping360.py.in
=> Add UDP socket connection functionality

README.md
=> README: Add pypi last version available

setup.py
=> setup: Update version to 0.1.0

README.md
This helps the user that have the package instaled to upgrade it automatically
=> README: Add --upgrade for pip install

setup.py
=> setup: Update to 0.1.1

.travis.yml
=> travis: Update pypi token

brping/pingmessage.py
Issue was reported by @NickNothom.
not tested.
=> pingmessage: don't crash when receiving unknown messages

setup.py
=> setup: Update to 0.1.2

generate/templates/device.py.in
Fixes bug that prevents UDP connections from working if initialised.
Fixes #113
=> generate:device.py.in - UDP `sendto` -> `send`

setup.py
=> setup: Update to 0.1.3 version

setup.py
=> setup: Update to 0.1.4 version

generate/templates/device.py.in
=> generate: add tiny sleep after send_break()

generate/templates/ping1d.py.in
=> generate: templates: ping1d: Add missing control functions
